/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpp_android_bitmap_NativeColorInverter */

#ifndef _Included_cpp_android_bitmap_NativeColorInverter
#define _Included_cpp_android_bitmap_NativeColorInverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp_android_bitmap_NativeColorInverter
 * Method:    invertColorsIn
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_cpp_android_bitmap_NativeColorInverter_invertColorsIn
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
