/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpp_android_obfuscatedkeyprovider_NativeKeyProvider */

#ifndef _Included_cpp_android_obfuscatedkeyprovider_NativeKeyProvider
#define _Included_cpp_android_obfuscatedkeyprovider_NativeKeyProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp_android_obfuscatedkeyprovider_NativeKeyProvider
 * Method:    provide
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cpp_android_obfuscatedkeyprovider_NativeKeyProvider_provide
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
